# Generated by Django 4.2 on 2023-06-28 06:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0006_order_delivery_status'),
        ('transactions', 'recreate_transactions_order'),
    ]

    operations = [
    ]
