# Generated by Django 4.2 on 2024-02-10 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0007_merge_20230628_1414'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='apartment_address',
            field=models.CharField(max_length=250, null=True),
        ),
    ]
