# Generated by Django 4.2 on 2023-04-26 17:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(choices=[('computers_laptops', 'Computers & Laptops'), ('smartphones_tablets', 'Smartphones & Tablets'), ('gaming_consoles_accessories', 'Gaming Consoles & Accessories'), ('audio_video_equipment', 'Audio & Video Equipment'), ('storage_devices', 'Storage Devices')], db_index=True, max_length=50)),
                ('slug', models.SlugField(max_length=255, unique=True)),
            ],
            options={
                'verbose_name_plural': 'categories',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('units_sold', models.IntegerField(default=0)),
                ('description', models.TextField()),
                ('slug', models.SlugField(max_length=255)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('stock', models.IntegerField()),
                ('image', models.ImageField(upload_to='products/images/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product', to='products.category')),
            ],
            options={
                'verbose_name_plural': 'products',
                'ordering': ('-created_at',),
            },
        ),
    ]
