# Generated by Django 4.2 on 2023-06-26 15:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0013_cartitem_unit_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitem',
            name='unit_price',
        ),
    ]
