# Generated by Django 4.2 on 2023-07-09 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0016_alter_review_unique_together_rating_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='title',
            field=models.CharField(default='review', max_length=120),
            preserve_default=False,
        ),
    ]
