# Generated by Django 4.2 on 2023-07-12 14:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('products', '0017_review_title'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='review',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='review',
            name='rating',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='review', to='products.rating'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='review',
            unique_together={('rating', 'user')},
        ),
        migrations.RemoveField(
            model_name='review',
            name='product',
        ),
    ]
